services: mongodb
language: ruby
script: "bundle exec rake spec"
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
env:
  - CODECLIMATE_REPO_TOKEN=891d362268d07d6ff0f5534f92252b6195f6be8795054d3627643eb6314a8c9e
gemfile:
  - gemfiles/active_record_32.gemfile
  - gemfiles/active_record_40.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/mongoid_3.gemfile
  - gemfiles/mongoid_4.gemfile
notifications:
  email: false
matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/active_record_32.gemfile
addons:
  code_climate:
    repo_token: 891d362268d07d6ff0f5534f92252b6195f6be8795054d3627643eb6314a8c9e